# Generated by Django 2.2.11 on 2021-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tumblr_post_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
